#!/usr/bin/env node
/* Generate CONTRAST.md — WCAG 2.x contrast ratios for every text/background
   pair the design system uses, both themes. Run after any token change:
   node scripts/contrast.js                                                */

import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));

const light = {
  paper: [220, 26, 96],
  surface: [0, 0, 100],
  "surface-2": [220, 30, 94],
  ink: [222, 34, 13],
  "ink-muted": [220, 14, 37],
  accent: [256, 60, 56],
  "accent-ink": [0, 0, 100],
  link: [256, 64, 48],
  "accent-soft": [256, 82, 95],
  "accent-soft-ink": [256, 58, 45],
  "accent-2": [38, 92, 50],
  "accent-2-ink": [30, 82, 20],
  "accent-2-soft": [43, 96, 92],
  "accent-2-soft-ink": [30, 88, 30],
  "accent-2-line": [40, 85, 62],
  ok: [150, 55, 30],
  "ok-ink": [120, 40, 98],
  "ok-soft": [150, 52, 93],
  danger: [358, 62, 44],
  "danger-ink": [0, 0, 100],
  "danger-soft": [358, 82, 96],
};

const dark = {
  paper: [224, 32, 8],
  surface: [223, 28, 11],
  "surface-2": [222, 26, 15],
  ink: [220, 32, 94],
  "ink-muted": [220, 16, 71],
  accent: [256, 88, 78],
  "accent-ink": [256, 44, 10],
  link: [256, 92, 82],
  "accent-soft": [256, 40, 22],
  "accent-soft-ink": [256, 90, 85],
  "accent-2": [40, 92, 62],
  "accent-2-ink": [36, 60, 12],
  "accent-2-soft": [36, 38, 20],
  "accent-2-soft-ink": [42, 95, 74],
  "accent-2-line": [40, 55, 42],
  ok: [150, 56, 60],
  "ok-ink": [150, 40, 9],
  "ok-soft": [150, 28, 16],
  danger: [358, 88, 74],
  "danger-ink": [358, 40, 12],
  "danger-soft": [358, 36, 17],
};

/* [what it styles, fg token, bg token, size class: normal|large] */
const pairs = [
  ["Body text on content card", "ink", "surface", "normal"],
  ["Body text on paper", "ink", "paper", "normal"],
  ["Body text on surface-2 (objectives, pre)", "ink", "surface-2", "normal"],
  ["Muted text on content card", "ink-muted", "surface", "normal"],
  ["Muted text on surface-2 (chips, kickers)", "ink-muted", "surface-2", "normal"],
  ["Muted text on paper (wordmark, module label)", "ink-muted", "paper", "normal"],
  ["Links on content card", "link", "surface", "normal"],
  ["Wikilink / note title / term pill", "accent-soft-ink", "accent-soft", "normal"],
  ["Objectives kicker on surface-2", "accent-soft-ink", "surface-2", "normal"],
  ["Warning title on danger-soft", "danger", "danger-soft", "normal"],
  ["Body text inside warning callout", "ink", "danger-soft", "normal"],
  ["Links inside warning callout", "link", "danger-soft", "normal"],
  ["Body text inside note callout", "ink", "accent-soft", "normal"],
  ["Links inside note callout", "link", "accent-soft", "normal"],
  ["Checkpoint title on ok-soft", "ok", "ok-soft", "normal"],
  ["Body text inside checkpoint", "ink", "ok-soft", "normal"],
  ["Tag / soft-pill highlight text", "accent-2-soft-ink", "accent-2-soft", "normal"],
  ["Ink over amber highlight wash", "accent-2-ink", "accent-2", "normal"],
  ["Play tile / callout ico glyph", "accent-ink", "accent", "large"],
  ["Warning ico glyph", "danger-ink", "danger", "large"],
  ["Checkpoint mark glyph", "ok-ink", "ok", "large"],
];

function hslToRgb([h, s, l]) {
  s /= 100;
  l /= 100;
  const k = (n) => (n + h / 30) % 12;
  const a = s * Math.min(l, 1 - l);
  const f = (n) => l - a * Math.max(-1, Math.min(k(n) - 3, Math.min(9 - k(n), 1)));
  return [f(0), f(8), f(4)];
}

function luminance(rgb) {
  const [r, g, b] = rgb.map((c) => (c <= 0.03928 ? c / 12.92 : ((c + 0.055) / 1.055) ** 2.4));
  return 0.2126 * r + 0.7152 * g + 0.0722 * b;
}

function ratio(fg, bg) {
  const l1 = luminance(hslToRgb(fg));
  const l2 = luminance(hslToRgb(bg));
  const [hi, lo] = l1 > l2 ? [l1, l2] : [l2, l1];
  return (hi + 0.05) / (lo + 0.05);
}

function table(tokens, themeName) {
  const rows = pairs.map(([label, fg, bg, size]) => {
    const r = ratio(tokens[fg], tokens[bg]);
    const need = size === "large" ? 3 : 4.5;
    const verdict = r >= need ? "pass" : "**FAIL**";
    return `| ${label} | \`${fg}\` on \`${bg}\` | ${r.toFixed(2)}:1 | ${need}:1 | ${verdict} |`;
  });
  return [
    `## ${themeName}`,
    "",
    "| Pair | Tokens | Ratio | AA needs | Verdict |",
    "| --- | --- | --- | --- | --- |",
    ...rows,
    "",
  ].join("\n");
}

const doc = [
  "# Contrast verification — GRID design system",
  "",
  "Generated by `scripts/contrast.js` from the token values in",
  "`css/grid-tokens.css`. Regenerate after ANY token change.",
  '"Large" rows are bold glyphs ≥ 18.66px equivalent (AA requires 3:1).',
  "Canvas receives the light theme only.",
  "",
  table(light, "Light (the Canvas theme)"),
  table(dark, "Dark (preview/print targets only)"),
].join("\n");

writeFileSync(join(here, "..", "CONTRAST.md"), doc + "\n");
const fails = (doc.match(/FAIL/g) ?? []).length;
console.log(`CONTRAST.md written — ${pairs.length} pairs × 2 themes, ${fails} failures`);
