#!/usr/bin/env node
/* Generate CONTRAST.md — WCAG 2.x contrast ratios for every text/background
   pair the design system uses, both themes. Run after any token change:
   node scripts/contrast.js                                                */

import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { readTokenBlocks, tripletsOf } from "../pipeline/tokens.js";

const here = dirname(fileURLToPath(import.meta.url));

// Token values come straight from css/grid-tokens.css — no hand-mirrored
// copy to drift. tripletsOf() yields { token: [h, s, l] } for the WCAG math
// below. readTokenBlocks() also asserts the two dark blocks stay in sync.
const blocks = readTokenBlocks();
const light = tripletsOf(blocks.light);
const dark = tripletsOf(blocks.dark);

/* [what it styles, fg token, bg token, size class: normal|large] */
const pairs = [
  ["Body text on content card", "ink", "surface", "normal"],
  ["Body text on paper", "ink", "paper", "normal"],
  ["Body text on surface-2 (objectives, pre)", "ink", "surface-2", "normal"],
  ["Muted text on content card", "ink-muted", "surface", "normal"],
  ["Muted text on surface-2 (chips, kickers)", "ink-muted", "surface-2", "normal"],
  ["Muted text on paper (wordmark, module label)", "ink-muted", "paper", "normal"],
  ["Links on content card", "link", "surface", "normal"],
  ["Wikilink / note title / term pill", "accent-soft-ink", "accent-soft", "normal"],
  ["Objectives kicker on surface-2", "accent-soft-ink", "surface-2", "normal"],
  ["Warning title on danger-soft", "danger", "danger-soft", "normal"],
  ["Body text inside warning callout", "ink", "danger-soft", "normal"],
  ["Links inside warning callout", "link", "danger-soft", "normal"],
  ["Body text inside note callout", "ink", "accent-soft", "normal"],
  ["Links inside note callout", "link", "accent-soft", "normal"],
  ["Checkpoint title on ok-soft", "ok", "ok-soft", "normal"],
  ["Body text inside checkpoint", "ink", "ok-soft", "normal"],
  ["Tag / soft-pill highlight text", "accent-2-soft-ink", "accent-2-soft", "normal"],
  ["Ink over amber highlight wash", "accent-2-ink", "accent-2", "normal"],
  ["Play tile / callout ico glyph", "accent-ink", "accent", "large"],
  ["Warning ico glyph", "danger-ink", "danger", "large"],
  ["Checkpoint mark glyph", "ok-ink", "ok", "large"],
  ["Card marker border on surface (non-text 3:1)", "card-line", "surface", "large"],
  ["Good-panel text on ok-soft (video compare)", "ok-soft-ink", "ok-soft", "normal"],
  ["Bad-panel text on danger-soft (video compare)", "danger-soft-ink", "danger-soft", "normal"],
];

function hslToRgb([h, s, l]) {
  s /= 100;
  l /= 100;
  const k = (n) => (n + h / 30) % 12;
  const a = s * Math.min(l, 1 - l);
  const f = (n) => l - a * Math.max(-1, Math.min(k(n) - 3, Math.min(9 - k(n), 1)));
  return [f(0), f(8), f(4)];
}

function luminance(rgb) {
  const [r, g, b] = rgb.map((c) => (c <= 0.03928 ? c / 12.92 : ((c + 0.055) / 1.055) ** 2.4));
  return 0.2126 * r + 0.7152 * g + 0.0722 * b;
}

function ratio(fg, bg) {
  const l1 = luminance(hslToRgb(fg));
  const l2 = luminance(hslToRgb(bg));
  const [hi, lo] = l1 > l2 ? [l1, l2] : [l2, l1];
  return (hi + 0.05) / (lo + 0.05);
}

function table(tokens, themeName) {
  const rows = pairs.map(([label, fg, bg, size]) => {
    const r = ratio(tokens[fg], tokens[bg]);
    const need = size === "large" ? 3 : 4.5;
    const verdict = r >= need ? "pass" : "**FAIL**";
    return `| ${label} | \`${fg}\` on \`${bg}\` | ${r.toFixed(2)}:1 | ${need}:1 | ${verdict} |`;
  });
  return [
    `## ${themeName}`,
    "",
    "| Pair | Tokens | Ratio | AA needs | Verdict |",
    "| --- | --- | --- | --- | --- |",
    ...rows,
    "",
  ].join("\n");
}

const doc = [
  "# Contrast verification — GRID design system",
  "",
  "Generated by `scripts/contrast.js` from the token values in",
  "`css/grid-tokens.css`. Regenerate after ANY token change.",
  '"Large" rows are bold glyphs ≥ 18.66px equivalent (AA requires 3:1).',
  "Canvas receives the light theme only.",
  "",
  table(light, "Light (the Canvas theme)"),
  table(dark, "Dark (preview/print targets only)"),
].join("\n");

writeFileSync(join(here, "..", "CONTRAST.md"), doc + "\n");
const fails = (doc.match(/FAIL/g) ?? []).length;
console.log(`CONTRAST.md written — ${pairs.length} pairs × 2 themes, ${fails} failures`);
